### ISSUE TITLE
connectedCallback will have no children when DOM hasn't parsed yet

### ISSUE THREAD

**Issue by Danny-Engelman** [daviddarnes/heading-anchors#2]
```
  get headings() {
    return this.querySelectorAll(this.selector);
  }
```

Will return an empty NodeList because of:

https://dev.to/dannyengelman/web-component-developers-do-not-connect-with-the-connectedcallback-yet-4jo7

**Comment by daviddarnes** [comment]
This component *requires* the DOM to be parsed in order to know what to render, it relies on existing HTML on the page. Please stop spamming my components.

**Comment by Danny-Engelman** [comment]
Then make you WC wait for DOM.
You now present us with a car which you first have to push to the fuel station

**Comment by daviddarnes** [comment]
Are you using `type="module"` for the script tag? Using that means you can put the script anywhere on the page
